### ISSUE TITLE
Scrape COVID communications

### ISSUE THREAD

**Issue by johnnyapol** [johnnyapol/RPICovidScraper#13]
https://covid19.rpi.edu/communications

Can post a link (or maybe the post) to discord when available.

Thoughts: @elihschiff (since academic discord is our largest stakeholder)

**Comment by johnnyapol** [comment]
Recommendation: https://github.com/Alir3z4/html2text . I've used this with the pubsafe scraper and it worked fine.

**Comment by elihschiff** [comment]
I am all for this idea. I think it makes a lot of sense to add it to the bot.

**Comment by flour-ad** [comment]
Hello,
what exactly has to be done? you need some kind of script that would be able to scrape the content of the posts from mentioned site? I might be interested 👍

**Comment by elihschiff** [comment]
@flour-ad I believe the idea would be to add a function/script that runs when main.py is run. Right now I believe main.py is run in a cron job every 15min. This code would check if anything new has been posted to the communications link sent above and then if something new has been posted, send a webhook just like the main covid dashboard already does. The checking involves basic web scraping. And the sending of a webhook would involve using the html2text library to parse the info into text that could be sent on discord.
Also, you are probably going to want to keep track of the posts you have already read in the `.cache` file so that you dont send the same post twice.

Also, I see you are new to github as of today. I am just curious, are you an RPI student? Do you have any coding experience as well as any python experience? Dont let your experience stop you from working on the issue, I am just curious.

**Comment by flour-ad** [comment]
> @flour-ad I believe the idea would be to add a function/script that runs when main.py is run. Right now I believe main.py is run in a cron job every 15min. This code would check if anything new has been posted to the communications link sent above and then if something new has been posted, send a webhook just like the main covid dashboard already does. The checking involves basic web scraping. And the sending of a webhook would involve using the html2text library to parse the info into text that could be sent on discord.
> Also, you are probably going to want to keep track of the posts you have already read in the `.cache` file so that you dont send the same post twice.
> 
> Also, I see you are new to github as of today. I am just curious, are you an RPI student? Do you have any coding experience as well as any python experience? Dont let your experience stop you from working on the issue, I am just curious.

Nope - I am not a RPI Student. Right now I am about to finish my master's degree in Electronics. I have about a year and a half of professional experience as a python programmer, and I began to learn python about 2 years ago, so I am not a beginner. Now I decided to do some open source projects just for fun 👍

**Comment by flour-ad** [comment]
And as for the issue - sounds good to me. You can assign me for that and I will try to start working on this tomorrow.

**Comment by flour-ad** [comment]
Just to make sure - when you enter https://covid19.rpi.edu/communications, only the snippets of the full message can be seen. You want the whole message to be posted to discord, right? So for example, for the post from February 24, 2021, you want the full content (https://covid19.rpi.edu/announcements/pandemic-safety-protocols-and-trigger-points)? 

And you want only the post content, or the author, date etc. as well?

**Comment by elihschiff** [comment]
I would say ideally send as much info and as much of the message as possible, the only limit being the 2000 characters before discord cuts you off

**Comment by flour-ad** [comment]
> I would say ideally send as much info and as much of the message as possible, the only limit being the 2000 characters before discord cuts you off

Hello, 
here you can see what I got by now https://github.com/flourad/RPICovidScraper/blob/rpi_communications_script/rpi_scraper.py 

As for now, announcement_data is a dictionary which contains author, date and content of every new post. You can see that I also pushed example cache file (.cache_sample) - it contains all the links, but I modified the first line by adding "* ", so it treats this link as a new one. Also the update_cache line is commented out, so you can run this script a few times to investigate the results. Of course this dictionary can be later processed, to create final string that would be posted on discord after linking this script to the main part of your app. 

You also mentioned that the character limit is equal to 2000 - I think that most of the posts are longer than that, so we can for example just limit the length of the post content that will be posted and add an information that full post is available on RPI site to satisfy this requirement. 

Let me know what do you think!

**Comment by elihschiff** [comment]
@flour-ad your link isn't working for me

As for limiting the post. I say just cut it off at 1997 characters and add 3 dots at the end...
Then you can add the link to the full post in the webhook. It is hard for me to exactly visualize this though without seeing a working webhook, so feel free to get creative with what you think will look and work the best.

**Comment by flour-ad** [comment]
> @flour-ad your link isn't working for me
> 
> As for limiting the post. I say just cut it off at 1997 characters and add 3 dots at the end...
> Then you can add the link to the full post in the webhook. It is hard for me to exactly visualize this though without seeing a working webhook, so feel free to get creative with what you think will look and work the best.

I created a pull request -> https://github.com/johnnyapol/RPICovidScraper/pull/19
