### ISSUE TITLE
Have multiple positive thumbnails / negative thumbnails

### ISSUE THREAD

**Issue by johnnyapol** [johnnyapol/RPICovidScraper#6]
https://github.com/johnnyapol/RPICovidScraper/commit/c6a439038ecba39d27a4674a3898d979795d397c brought a change to differentiate the thumbnails based on 24 hour case data.

It would be cool to have two separate arrays, positive_thumbnails and negative_thumbnails that are randomly chosen at runtime.

**Comment by chrisj1** [comment]
Good idea
